# Generated by Django 2.2.6 on 2020-01-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0006_solve'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=30),
        ),
    ]
