# Generated by Django 2.2.6 on 2020-03-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0007_question_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='solve',
            name='user_name',
            field=models.CharField(default='esakiryota', max_length=200),
        ),
    ]
