# Generated by Django 2.2.6 on 2020-03-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0009_introduce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduce',
            name='author',
        ),
        migrations.AddField(
            model_name='introduce',
            name='name',
            field=models.CharField(default='匿名', max_length=200),
        ),
        migrations.AlterField(
            model_name='introduce',
            name='place',
            field=models.CharField(default='some place', max_length=200),
        ),
    ]
