# Generated by Django 2.2.6 on 2020-03-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0010_auto_20200318_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduce',
            name='published_date',
        ),
    ]
