# Generated by Django 2.2.6 on 2020-03-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0011_remove_introduce_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduce',
            name='intro',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
