# Generated by Django 2.2.6 on 2020-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0015_questionsolve'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbox',
            name='comment',
            field=models.CharField(default='ここにコメントがかかれます', max_length=300),
        ),
        migrations.AddField(
            model_name='questionsolve',
            name='comment',
            field=models.CharField(default='ここにコメントがかかれます', max_length=300),
        ),
    ]
