# Generated by Django 2.2.6 on 2020-03-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0016_auto_20200322_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbox',
            name='user_name',
            field=models.CharField(default='noname', max_length=200),
        ),
        migrations.AlterField(
            model_name='questionsolve',
            name='comment',
            field=models.CharField(default='ここにコメントをお願いします。', max_length=300),
        ),
    ]
