# Generated by Django 2.2.6 on 2020-03-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0017_auto_20200324_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbox',
            name='bool',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionsolve',
            name='bool',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
