# Generated by Django 2.2.6 on 2020-03-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0019_auto_20200325_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbox',
            name='title',
            field=models.CharField(default='タイトル', max_length=200),
        ),
    ]
