# Generated by Django 2.2.6 on 2020-04-01 16:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practiceblog', '0020_auto_20200325_0351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageBox',
        ),
    ]
