# Generated by Django 2.2.6 on 2020-04-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0021_auto_20200402_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebox',
            name='cate',
            field=models.CharField(choices=[('数学', '数学'), ('英語', '英語'), ('理科', '理科')], default='科目', max_length=200),
        ),
    ]
