# Generated by Django 2.2.6 on 2020-05-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0022_auto_20200418_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='solve',
            name='score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='solve',
            name='cate',
            field=models.CharField(choices=[('数学', '数学'), ('英語', '英語'), ('理科', '理科')], default='数学', max_length=200),
        ),
        migrations.AlterField(
            model_name='solve',
            name='user_name',
            field=models.CharField(max_length=200),
        ),
    ]
