# Generated by Django 2.2.6 on 2020-04-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0022_auto_20200406_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebox',
            name='title',
            field=models.CharField(default='タイトル', max_length=200),
        ),
    ]
