# Generated by Django 2.2.6 on 2020-05-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0023_auto_20200503_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.CharField(choices=[('中学１年', '中学１年'), ('中学２年', '中学２年'), ('中学３年', '中学３年'), ('高校１年', '高校１年'), ('高校２年', '高校２年'), ('高校３年', '高校３年')], default='高校１年', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='indi_pub',
            field=models.CharField(choices=[('一般', '一般'), ('個人', '個人')], default='一般', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='new_old',
            field=models.CharField(choices=[('新規', '新規'), ('復習', '復習')], default='新規', max_length=200),
        ),
    ]
