# Generated by Django 2.2.6 on 2020-08-10 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0025_questionbox_limited_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbox',
            name='limited_time',
        ),
        migrations.AddField(
            model_name='question',
            name='limited_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
