# Generated by Django 2.2.19 on 2021-04-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0027_teacherstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstudent',
            name='teacher_student',
            field=models.CharField(default='先生_生徒', max_length=200),
        ),
    ]
