# Generated by Django 2.2.6 on 2022-03-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0025_auto_20200406_1320'),
        ('practiceblog', '0028_teacherstudent_teacher_student'),
    ]

    operations = [
    ]
