# Generated by Django 2.2.6 on 2022-06-12 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0029_merge_20220305_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='先生_生徒', max_length=200)),
                ('url_token', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='solve',
            name='user_name',
            field=models.CharField(max_length=200),
        ),
    ]
