# Generated by Django 2.2.6 on 2022-07-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0030_auto_20220612_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlist',
            name='participants',
            field=models.IntegerField(default=0),
        ),
    ]
