# Generated by Django 3.0.14 on 2022-09-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceblog', '0033_profilelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelist',
            name='display_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
