# Generated by Django 2.2.6 on 2022-06-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(default='no', max_length=200)),
                ('content', models.TextField(default='<svg></svg>')),
            ],
        ),
    ]
